### ISSUE TITLE
try `--no-install-recommends`

### ISSUE THREAD

**Issue by cbm755** [natmarbal/octave-workspace#2]
`apt install -y --no-install-recommends octave` might give a slimmer install.

**Comment by natmarbal** [comment]
If `--no-install-recommends` is used, the following pops up when the Octave GUI launches:
<img width="600" alt="Screen Shot 2022-08-31 at 20 34 16" src="https://user-images.githubusercontent.com/108496590/187827364-cd032109-ca8b-4fd8-a166-662cfe57aa68.png">
<img width="600" alt="Screen Shot 2022-08-31 at 20 34 32" src="https://user-images.githubusercontent.com/108496590/187827374-7ef4804d-2a52-48e7-acf4-90597dc2a829.png">

A comparison of the builds:
`apt install -y --no-install-recommends octave`
![Screen Shot 2022-08-31 at 20 36 16](https://user-images.githubusercontent.com/108496590/187827526-bdebfce6-cf34-4a51-b34b-e40631926de7.png)

`apt install -y octave`
![Screen Shot 2022-08-31 at 20 38 05](https://user-images.githubusercontent.com/108496590/187827563-70773fdb-1bac-461f-8e58-19b7ce097e33.png)

I think I'm in favour of leaving it as `apt install -y octave`, since the installation is already slimmer with the layering, and it seems useful to have the Octave documentation available in the workspace.

**Comment by natmarbal** [comment]
`--no-install-recommends` makes a difference when building `octave-grader`.

Using `--no-install-recommends`:
<img width="600" alt="Screen Shot 2022-09-02 at 11 34 16" src="https://user-images.githubusercontent.com/108496590/188216665-4f751f0b-7606-49ec-82b1-dfc4826e992a.png">

Without `--no-install-recommends`:
<img width="600" alt="Screen Shot 2022-09-02 at 11 32 11" src="https://user-images.githubusercontent.com/108496590/188216678-7d347698-bf45-4189-bb3b-34ce7578f79a.png">
